In [3]:
import numpy as np

#using list
arry1 = np.array([1, 2, 3, 4])
print(arry1)
print(type(arry1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

#using tupple
array1 = np.array((1, 2, 3, 4))
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

# initialz array
array1 = np.zeros([2, 3])
print(array1)
print(type(array1))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [10]:
import numpy as np

# get data type
array1 = np.array([1, 2, 3, 4])
print(array1.dtype)

int32
